version: '3.7'

services:
  envoy-proxy:
    container_name: envoy-proxy
    build: 
      context: .
      dockerfile: docker/envoy/Dockerfile
    ports:
      - 8080:8080
      - 9000:9000
    volumes:
      - ./docker/envoy:/docker/envoy
    entrypoint: ["/entry.sh", "envoy", "-c", "/etc/envoy/envoy.yaml"]
