version: '3.7'

services:
  envoy:
    container_name: envoy-proxy
    image: envoyproxy/envoy-dev:0264041ec7a271c0291aa2d761856045c90aef7e
    ports:
      - 8080:8080
      - 9000:9000
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml



